name: CI-Pipepline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install depend
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make

      - name: Building program
        run: make all
        working-directory: ./src

      - name: Upload binaries to artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordcounter-artifact
          path: usr/bin/wordcounter
          retention-days: 1

  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: wordcounter-artifact
          path: ./usr/bin

      - run: chmod +x ./usr/bin/wordcounter

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install depend
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make

      - name: Scripts tests
        run: chmod +x run_test.sh
        working-directory: ./cicd

      - name: run scripts tests
        run: ./run_test.sh
        working-directory: ./cicd

  PackagerNotMyLover:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: wordcounter-artifact
          path: ./usr/bin

      - name: Build deb-package
        run: |
          dpkg-deb --build . Wordcounter.deb

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: wc-deb-package
          path: "Wordcounter.deb"
          retention-days: 1

# Practice 3: dockerfiles
  Deploy:
    needs: PackagerNotMyLover
    runs-on: ubuntu-latest

    steps:
      - name: Q docker
        run: docker --version

      - name: clone
        uses: actions/checkout@v4

      - name: Download deb-package
        uses: actions/download-artifact@v4
        with:
          name: wc-deb-package
          path: .

      - name: Build docker image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/wordcounter:1.0.0 -f cicd/Dockerfile .
          docker tag ${{ vars.DOCKER_USERNAME }}/wordcounter:1.0.0 ${{ vars.DOCKER_USERNAME }}/wordcounter:latest

      - name: Deploy on docker container
        run: docker run ${{ vars.DOCKER_USERNAME }}/wordcounter "- Don't say his name! - Whose name is it? - Tarasevich."

      - name: Docker Log in
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Real Deploy
        run: docker push -a ${{ vars.DOCKER_USERNAME }}/wordcounter
